# SQLite ou MySQL
Banco: SQLite
MySQL:
  user: root
  host: 127.0.0.1:3306
  database: test
  password: ''
Permission-armazem: 'NexusArmazem.use'
Permission-armazem-admin: 'NexusArmazem.admin.use'
# coloque em ordem crescente (do maior bonus até o menor)
BonusVIP:
  MVPM:
    # O bonus fica 75%
    bonus: 1.75
    permission: 'NexusArmazem.mvpm'
  MVP:
    # O bonus fica 50%
    bonus: 1.50
    permission: 'NexusArmazem.mvp'
  VIP:
    # O bonus fica 25%
    bonus: 1.25
    permission: 'NexusArmazem.vip'
Itens-armazem:
  cactus:
    name: '&6Cactos'
    ID: 81
    price: 15
    recolher: false
  melon:
    name: '&aMelancia'
    ID: 360
    price: 10
    recolher: true
  fungo:
    name: '&cFungo do Nether'
    ID: 372
    price: 32
    # pode recolher?
    recolher: true
  limite:
    name: '&6Limite armazém'
    ID: 399
    price: 0
    recolher: false
Limite-Configuration:
  default:
    name: 'Nível 0'
    next: 'level-1'
    limite: 560
    price: 12500
  level-1:
    name: 'Nível 1'
    next: 'level-2'
    limite: 750
    price: 25000
  level-2:
    name: 'Nível 2'
    next: 'level-3'
    limite: 1250
    price: 50000
  level-3:
    name: 'Nível 3'
    next: 'finish'
    limite: 2500
    price: 100000

InventoryConfiguration:
  # nome da key dos itens-armazem (que estão acima)
  cactus:
    lore:
      - ''
      - ' &fArmazém: &7@quantidade'
      - ' &fVenda seus drops:&a $@money'
      - ''
      - '&eClique para vender.'
    slot: 11
  melon:
    lore:
      - ''
      - ' &fArmazém: &7@quantidade'
      - ' &fVenda seus drops:&a $@money'
      - ''
      - '&eClique com &fesquerdo &epara vender.'
      - '&eClique com &fdireito &epara recolher.'
    slot: 13
  fungo:
    lore:
      - ''
      - ' &fArmazém: &7@quantidade'
      - ' &fVenda seus drops:&a $@money'
      - ''
      - '&eClique com &fesquerdo &epara vender.'
      - '&eClique com &fdireito &epara recolher.'
    slot: 15
  limite:
    lore-upgrade:
      - '&6&lUP &7a capacidade do'
      - '&7seu armazem.'
      - ''
      - ' &fCapacidade: &b@atual -> @futuro'
      - ' &fCusto: §a$@dinheiro'
      - ''
      - '&eClique para upar!'
    lore-finish:
      - '&cVocê atingiu o limite máximo'
      - ''
      - '&fCapacidade atual: @atual'
    slot: 31